<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LowonganSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('lowongans')->insert([
            [
                'judul' => 'LOWONGAN KERJA PT MITRA PEDAGANG INDONESIA Tbk.',
                'tgl_akhir_daftar' => '2025-03-01',
                'perusahaan' => 'PT MITRA PEDAGANG INDONESIA Tbk.',
                'deskripsi' => 'Mempromosikan aplikasi MPStore di sosial media',
                'jurusan' => 'Teknik Jaringan Komputer, Rekayasa Perangkat Lunak',
                'posisi' => 'Marketing',
                'penempatan' => 'Bangkalan',
                'gaji' => '2000000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'LOWONGAN KERJA PT GG ABADI',
                'tgl_akhir_daftar' => '2025-03-03',
                'perusahaan' => 'PT GG Abadi',
                'deskripsi' => 'Melakukan perawatan dan perbaikan mesin kendaraan.',
                'jurusan' => 'Teknik Kendaraan Ringan Otomotif, Teknik Sepeda Motor',
                'posisi' => 'Mekanik',
                'penempatan' => 'Surabaya',
                'gaji' => '5000000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'LOWONGAN KERJA PT TEKNOLOGI MAJU',
                'tgl_akhir_daftar' => '2025-03-04',
                'perusahaan' => 'PT Teknologi Maju',
                'deskripsi' => 'Mengembangkan aplikasi berbasis web dan mobile.',
                'jurusan' => 'Rekayasa Perangkat Lunak, Teknik Jaringan Komputer',
                'posisi' => 'Software Engineer',
                'penempatan' => 'Bandung',
                'gaji' => '10000000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'LOWONGAN KERJA PT SINAR JAYA',
                'tgl_akhir_daftar' => '2025-03-06',
                'perusahaan' => 'PT Sinar Jaya',
                'deskripsi' => 'Membantu administrasi dan pengelolaan data perusahaan.',
                'jurusan' => 'Teknik Elektronika Industri, Teknik Kimia Industri',
                'posisi' => 'Administrasi',
                'penempatan' => 'Yogyakarta',
                'gaji' => '4500000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'LOWONGAN KERJA PT ANUGERAH SEJAHTERA',
                'tgl_akhir_daftar' => '2025-03-08',
                'perusahaan' => 'PT Anugerah Sejahtera',
                'deskripsi' => 'Bertanggung jawab atas pengelolaan keuangan perusahaan.',
                'jurusan' => 'Teknik Kimia Industri, Teknik Instalasi Tenaga Listrik',
                'posisi' => 'Akuntan',
                'penempatan' => 'Medan',
                'gaji' => '8000000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'LOWONGAN KERJA PT MAJU BERSAMA',
                'tgl_akhir_daftar' => '2025-03-10',
                'perusahaan' => 'PT Maju Bersama',
                'deskripsi' => 'Menangani pengembangan strategi pemasaran perusahaan.',
                'jurusan' => 'Teknik Jaringan Komputer, Rekayasa Perangkat Lunak',
                'posisi' => 'Marketing Strategist',
                'penempatan' => 'Semarang',
                'gaji' => '9000000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'LOWONGAN KERJA PT SUKSES MAKMUR',
                'tgl_akhir_daftar' => '2025-03-12',
                'perusahaan' => 'PT Sukses Makmur',
                'deskripsi' => 'Melakukan pengelolaan sumber daya manusia.',
                'jurusan' => 'Teknik Pemesinan, Teknik Kendaraan Ringan Otomotif',
                'posisi' => 'HRD',
                'penempatan' => 'Malang',
                'gaji' => '7000000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'LOWONGAN KERJA PT DIGITAL NUSANTARA',
                'tgl_akhir_daftar' => '2025-03-14',
                'perusahaan' => 'PT Digital Nusantara',
                'deskripsi' => 'Membantu pengelolaan server dan keamanan jaringan perusahaan.',
                'jurusan' => 'Teknik Jaringan Komputer, Rekayasa Perangkat Lunak',
                'posisi' => 'Network Administrator',
                'penempatan' => 'Jakarta',
                'gaji' => '12000000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'LOWONGAN KERJA PT PRIMA TEKNOLOGI',
                'tgl_akhir_daftar' => '2025-03-16',
                'perusahaan' => 'PT Prima Teknologi',
                'deskripsi' => 'Menganalisis dan mengembangkan software berbasis AI.',
                'jurusan' => 'Rekayasa Perangkat Lunak, Teknik Jaringan Komputer',
                'posisi' => 'AI Engineer',
                'penempatan' => 'Surabaya',
                'gaji' => '15000000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'LOWONGAN KERJA PT MEGA KARYA',
                'tgl_akhir_daftar' => '2025-03-18',
                'perusahaan' => 'PT Mega Karya',
                'deskripsi' => 'Mengerjakan desain bangunan dan perencanaan konstruksi.',
                'jurusan' => 'Desain Pemodelan dan Informasi Bangunan',
                'posisi' => 'Drafter',
                'penempatan' => 'Bandung',
                'gaji' => '10000000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'LOWONGAN KERJA PT TRANS LOGISTICS',
                'tgl_akhir_daftar' => '2025-03-20',
                'perusahaan' => 'PT Trans Logistics',
                'deskripsi' => 'Mengatur distribusi barang dan logistik perusahaan.',
                'jurusan' => 'Teknik Pemesinan, Teknik Kendaraan Ringan Otomotif',
                'posisi' => 'Logistics Coordinator',
                'penempatan' => 'Yogyakarta',
                'gaji' => '8000000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'LOWONGAN KERJA PT GLOBAL MEDIA',
                'tgl_akhir_daftar' => '2025-03-22',
                'perusahaan' => 'PT Global Media',
                'deskripsi' => 'Mengelola konten media sosial dan strategi digital marketing.',
                'jurusan' => 'Rekayasa Perangkat Lunak, Teknik Jaringan Komputer',
                'posisi' => 'Social Media Specialist',
                'penempatan' => 'Semarang',
                'gaji' => '7000000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'LOWONGAN KERJA PT KARYA UTAMA',
                'tgl_akhir_daftar' => '2025-03-24',
                'perusahaan' => 'PT Karya Utama',
                'deskripsi' => 'Melakukan riset dan pengembangan sistem manufaktur.',
                'jurusan' => 'Teknik Pemesinan, Teknik Instalasi Tenaga Listrik',
                'posisi' => 'R&D Engineer',
                'penempatan' => 'Malang',
                'gaji' => '13000000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'LOWONGAN KERJA PT MAKMUR JAYA',
                'tgl_akhir_daftar' => '2025-03-26',
                'perusahaan' => 'PT Makmur Jaya',
                'deskripsi' => 'Menangani desain sistem kelistrikan gedung dan industri.',
                'jurusan' => 'Teknik Instalasi Tenaga Listrik, Teknik Elektronika Industri',
                'posisi' => 'Electrical Engineer',
                'penempatan' => 'Bali',
                'gaji' => '11000000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'LOWONGAN KERJA PT SINAR GEMILANG',
                'tgl_akhir_daftar' => '2025-03-28',
                'perusahaan' => 'PT Sinar Gemilang',
                'deskripsi' => 'Melakukan riset dan analisis bahan kimia industri.',
                'jurusan' => 'Teknik Kimia Industri, Teknik Elektronika Industri',
                'posisi' => 'Chemical Analyst',
                'penempatan' => 'Jakarta',
                'gaji' => '14000000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
